# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_auto_20160211_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message="Telefona numura formats: '+371 12345678'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
