# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0005_account_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='Postcode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('S', 'Sieviete'), ('V', 'Virietis')], max_length=1),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, default=0, max_length=8),
        ),
    ]
