# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0006_auto_20160211_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='contacting_password',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='+371 ', max_length=8),
        ),
    ]
