# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0007_auto_20160211_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='0', max_length=8),
        ),
    ]
