# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0008_auto_20160211_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fulfilled', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Parskaitijuma datums')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='email_adress',
            field=models.EmailField(default=datetime.datetime(2016, 3, 26, 16, 20, 3, 86158, tzinfo=utc), help_text='Formats, piemeram, cirvbank@inbox.lv', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='Postcode',
            field=models.CharField(blank=True, help_text='Piemeram, LV-4512', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, help_text='Piemeram, Liela iela 15a', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, help_text='Piemeram, Riga', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='contacting_password',
            field=models.CharField(blank=True, help_text='Parole, kas tiek izmantota sazinai ar banku', max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Formats, piemeram, +31721241275', max_length=12),
        ),
        migrations.AddField(
            model_name='transactiontemplate',
            name='account_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_from1', to='banking.Account'),
        ),
        migrations.AddField(
            model_name='transactiontemplate',
            name='account_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_to1', to='banking.Account'),
        ),
    ]
