# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0009_auto_20160326_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_adress',
        ),
    ]
