# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0010_remove_account_email_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_adress',
            field=models.EmailField(default=datetime.datetime(2016, 3, 26, 16, 33, 58, 211555, tzinfo=utc), help_text='Piemeram, cirvbank@inbox.lv', max_length=50),
            preserve_default=False,
        ),
    ]
