# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0011_account_email_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='date_created',
        ),
    ]
