# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0012_remove_account_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_adress',
        ),
        migrations.AddField(
            model_name='account',
            name='email_adresss',
            field=models.CharField(default=datetime.datetime(2016, 3, 26, 17, 50, 46, 873094, tzinfo=utc), help_text='Piemeram, cirvbank@inbox.lv', max_length=50),
            preserve_default=False,
        ),
    ]
