# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0013_auto_20160326_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontemplate',
            name='redirect_address',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
